name: my_custom_lint_package
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  # we will use analyzer for inspecting Dart files
  analyzer:
  analyzer_plugin:
  # custom_lint_builder will give us tools for writing lints
  custom_lint_builder: